// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes/location.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "datatypes/location.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DataTypes {

namespace {

const ::google::protobuf::Descriptor* Location_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Location_reflection_ = NULL;
const ::google::protobuf::Descriptor* LocationUpdate_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LocationUpdate_reflection_ = NULL;
struct LocationUpdateOneofInstance {
  const ::DataTypes::Location* inserted_;
  const ::DataTypes::Location* deleted_;
  const ::DataTypes::Location* updated_;
}* LocationUpdate_default_oneof_instance_ = NULL;

}  // namespace


void protobuf_AssignDesc_datatypes_2flocation_2eproto() {
  protobuf_AddDesc_datatypes_2flocation_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "datatypes/location.proto");
  GOOGLE_CHECK(file != NULL);
  Location_descriptor_ = file->message_type(0);
  static const int Location_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Location, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Location, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Location, description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Location, unit_mac_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Location, access_device_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Location, capture_device_),
  };
  Location_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Location_descriptor_,
      Location::default_instance_,
      Location_offsets_,
      -1,
      -1,
      -1,
      sizeof(Location),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Location, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Location, _is_default_instance_));
  LocationUpdate_descriptor_ = file->message_type(1);
  static const int LocationUpdate_offsets_[4] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(LocationUpdate_default_oneof_instance_, inserted_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(LocationUpdate_default_oneof_instance_, deleted_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(LocationUpdate_default_oneof_instance_, updated_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocationUpdate, update_type_),
  };
  LocationUpdate_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LocationUpdate_descriptor_,
      LocationUpdate::default_instance_,
      LocationUpdate_offsets_,
      -1,
      -1,
      -1,
      LocationUpdate_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocationUpdate, _oneof_case_[0]),
      sizeof(LocationUpdate),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocationUpdate, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocationUpdate, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_datatypes_2flocation_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Location_descriptor_, &Location::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LocationUpdate_descriptor_, &LocationUpdate::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_datatypes_2flocation_2eproto() {
  delete Location::default_instance_;
  delete Location_reflection_;
  delete LocationUpdate::default_instance_;
  delete LocationUpdate_default_oneof_instance_;
  delete LocationUpdate_reflection_;
}

void protobuf_AddDesc_datatypes_2flocation_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::DataTypes::protobuf_AddDesc_datatypes_2fdevices_2eproto();
  ::DataTypes::protobuf_AddDesc_datatypes_2fkey_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030datatypes/location.proto\022\tDataTypes\032\027d"
    "atatypes/devices.proto\032\023datatypes/key.pr"
    "oto\"\305\001\n\010Location\022\032\n\002id\030\001 \001(\0132\016.DataTypes"
    ".Key\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022"
    "\030\n\020unit_mac_address\030\004 \001(\t\022.\n\raccess_devi"
    "ce\030\005 \001(\0132\027.DataTypes.AccessDevice\0220\n\016cap"
    "ture_device\030\006 \001(\0132\030.DataTypes.CaptureDev"
    "ice\"\230\001\n\016LocationUpdate\022\'\n\010inserted\030\001 \001(\013"
    "2\023.DataTypes.LocationH\000\022&\n\007deleted\030\002 \001(\013"
    "2\023.DataTypes.LocationH\000\022&\n\007updated\030\003 \001(\013"
    "2\023.DataTypes.LocationH\000B\r\n\013update_typeBM"
    "\n\007ex.grpcZ<github.com/Enebra/ServiceCoor"
    "dinator/grpc/datatypes/location\242\002\003RTGb\006p"
    "roto3", 525);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "datatypes/location.proto", &protobuf_RegisterTypes);
  Location::default_instance_ = new Location();
  LocationUpdate::default_instance_ = new LocationUpdate();
  LocationUpdate_default_oneof_instance_ = new LocationUpdateOneofInstance();
  Location::default_instance_->InitAsDefaultInstance();
  LocationUpdate::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_datatypes_2flocation_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_datatypes_2flocation_2eproto {
  StaticDescriptorInitializer_datatypes_2flocation_2eproto() {
    protobuf_AddDesc_datatypes_2flocation_2eproto();
  }
} static_descriptor_initializer_datatypes_2flocation_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Location::kIdFieldNumber;
const int Location::kNameFieldNumber;
const int Location::kDescriptionFieldNumber;
const int Location::kUnitMacAddressFieldNumber;
const int Location::kAccessDeviceFieldNumber;
const int Location::kCaptureDeviceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Location::Location()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DataTypes.Location)
}

void Location::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  id_ = const_cast< ::DataTypes::Key*>(&::DataTypes::Key::default_instance());
  access_device_ = const_cast< ::DataTypes::AccessDevice*>(&::DataTypes::AccessDevice::default_instance());
  capture_device_ = const_cast< ::DataTypes::CaptureDevice*>(&::DataTypes::CaptureDevice::default_instance());
}

Location::Location(const Location& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DataTypes.Location)
}

void Location::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = NULL;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unit_mac_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  access_device_ = NULL;
  capture_device_ = NULL;
}

Location::~Location() {
  // @@protoc_insertion_point(destructor:DataTypes.Location)
  SharedDtor();
}

void Location::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unit_mac_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete id_;
    delete access_device_;
    delete capture_device_;
  }
}

void Location::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Location::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Location_descriptor_;
}

const Location& Location::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_datatypes_2flocation_2eproto();
  return *default_instance_;
}

Location* Location::default_instance_ = NULL;

Location* Location::New(::google::protobuf::Arena* arena) const {
  Location* n = new Location;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Location::Clear() {
// @@protoc_insertion_point(message_clear_start:DataTypes.Location)
  if (GetArenaNoVirtual() == NULL && id_ != NULL) delete id_;
  id_ = NULL;
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unit_mac_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && access_device_ != NULL) delete access_device_;
  access_device_ = NULL;
  if (GetArenaNoVirtual() == NULL && capture_device_ != NULL) delete capture_device_;
  capture_device_ = NULL;
}

bool Location::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DataTypes.Location)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .DataTypes.Key id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // optional string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DataTypes.Location.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_description;
        break;
      }

      // optional string description = 3;
      case 3: {
        if (tag == 26) {
         parse_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DataTypes.Location.description"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_unit_mac_address;
        break;
      }

      // optional string unit_mac_address = 4;
      case 4: {
        if (tag == 34) {
         parse_unit_mac_address:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_unit_mac_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->unit_mac_address().data(), this->unit_mac_address().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DataTypes.Location.unit_mac_address"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_access_device;
        break;
      }

      // optional .DataTypes.AccessDevice access_device = 5;
      case 5: {
        if (tag == 42) {
         parse_access_device:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_access_device()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_capture_device;
        break;
      }

      // optional .DataTypes.CaptureDevice capture_device = 6;
      case 6: {
        if (tag == 50) {
         parse_capture_device:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_capture_device()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DataTypes.Location)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DataTypes.Location)
  return false;
#undef DO_
}

void Location::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DataTypes.Location)
  // optional .DataTypes.Key id = 1;
  if (this->has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->id_, output);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DataTypes.Location.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // optional string description = 3;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DataTypes.Location.description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->description(), output);
  }

  // optional string unit_mac_address = 4;
  if (this->unit_mac_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->unit_mac_address().data(), this->unit_mac_address().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DataTypes.Location.unit_mac_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->unit_mac_address(), output);
  }

  // optional .DataTypes.AccessDevice access_device = 5;
  if (this->has_access_device()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->access_device_, output);
  }

  // optional .DataTypes.CaptureDevice capture_device = 6;
  if (this->has_capture_device()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->capture_device_, output);
  }

  // @@protoc_insertion_point(serialize_end:DataTypes.Location)
}

::google::protobuf::uint8* Location::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataTypes.Location)
  // optional .DataTypes.Key id = 1;
  if (this->has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->id_, target);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DataTypes.Location.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // optional string description = 3;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DataTypes.Location.description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->description(), target);
  }

  // optional string unit_mac_address = 4;
  if (this->unit_mac_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->unit_mac_address().data(), this->unit_mac_address().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DataTypes.Location.unit_mac_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->unit_mac_address(), target);
  }

  // optional .DataTypes.AccessDevice access_device = 5;
  if (this->has_access_device()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, *this->access_device_, target);
  }

  // optional .DataTypes.CaptureDevice capture_device = 6;
  if (this->has_capture_device()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, *this->capture_device_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DataTypes.Location)
  return target;
}

int Location::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:DataTypes.Location)
  int total_size = 0;

  // optional .DataTypes.Key id = 1;
  if (this->has_id()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->id_);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional string description = 3;
  if (this->description().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->description());
  }

  // optional string unit_mac_address = 4;
  if (this->unit_mac_address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->unit_mac_address());
  }

  // optional .DataTypes.AccessDevice access_device = 5;
  if (this->has_access_device()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->access_device_);
  }

  // optional .DataTypes.CaptureDevice capture_device = 6;
  if (this->has_capture_device()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->capture_device_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Location::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DataTypes.Location)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Location* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Location>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DataTypes.Location)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DataTypes.Location)
    MergeFrom(*source);
  }
}

void Location::MergeFrom(const Location& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DataTypes.Location)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_id()) {
    mutable_id()->::DataTypes::Key::MergeFrom(from.id());
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.description().size() > 0) {

    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
  if (from.unit_mac_address().size() > 0) {

    unit_mac_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.unit_mac_address_);
  }
  if (from.has_access_device()) {
    mutable_access_device()->::DataTypes::AccessDevice::MergeFrom(from.access_device());
  }
  if (from.has_capture_device()) {
    mutable_capture_device()->::DataTypes::CaptureDevice::MergeFrom(from.capture_device());
  }
}

void Location::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DataTypes.Location)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Location::CopyFrom(const Location& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DataTypes.Location)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Location::IsInitialized() const {

  return true;
}

void Location::Swap(Location* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Location::InternalSwap(Location* other) {
  std::swap(id_, other->id_);
  name_.Swap(&other->name_);
  description_.Swap(&other->description_);
  unit_mac_address_.Swap(&other->unit_mac_address_);
  std::swap(access_device_, other->access_device_);
  std::swap(capture_device_, other->capture_device_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Location::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Location_descriptor_;
  metadata.reflection = Location_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Location

// optional .DataTypes.Key id = 1;
bool Location::has_id() const {
  return !_is_default_instance_ && id_ != NULL;
}
void Location::clear_id() {
  if (GetArenaNoVirtual() == NULL && id_ != NULL) delete id_;
  id_ = NULL;
}
const ::DataTypes::Key& Location::id() const {
  // @@protoc_insertion_point(field_get:DataTypes.Location.id)
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
::DataTypes::Key* Location::mutable_id() {
  
  if (id_ == NULL) {
    id_ = new ::DataTypes::Key;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.Location.id)
  return id_;
}
::DataTypes::Key* Location::release_id() {
  // @@protoc_insertion_point(field_release:DataTypes.Location.id)
  
  ::DataTypes::Key* temp = id_;
  id_ = NULL;
  return temp;
}
void Location::set_allocated_id(::DataTypes::Key* id) {
  delete id_;
  id_ = id;
  if (id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.Location.id)
}

// optional string name = 2;
void Location::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Location::name() const {
  // @@protoc_insertion_point(field_get:DataTypes.Location.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Location::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DataTypes.Location.name)
}
 void Location::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DataTypes.Location.name)
}
 void Location::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DataTypes.Location.name)
}
 ::std::string* Location::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:DataTypes.Location.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Location::release_name() {
  // @@protoc_insertion_point(field_release:DataTypes.Location.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Location::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:DataTypes.Location.name)
}

// optional string description = 3;
void Location::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Location::description() const {
  // @@protoc_insertion_point(field_get:DataTypes.Location.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Location::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DataTypes.Location.description)
}
 void Location::set_description(const char* value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DataTypes.Location.description)
}
 void Location::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DataTypes.Location.description)
}
 ::std::string* Location::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:DataTypes.Location.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Location::release_description() {
  // @@protoc_insertion_point(field_release:DataTypes.Location.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Location::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:DataTypes.Location.description)
}

// optional string unit_mac_address = 4;
void Location::clear_unit_mac_address() {
  unit_mac_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Location::unit_mac_address() const {
  // @@protoc_insertion_point(field_get:DataTypes.Location.unit_mac_address)
  return unit_mac_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Location::set_unit_mac_address(const ::std::string& value) {
  
  unit_mac_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DataTypes.Location.unit_mac_address)
}
 void Location::set_unit_mac_address(const char* value) {
  
  unit_mac_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DataTypes.Location.unit_mac_address)
}
 void Location::set_unit_mac_address(const char* value, size_t size) {
  
  unit_mac_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DataTypes.Location.unit_mac_address)
}
 ::std::string* Location::mutable_unit_mac_address() {
  
  // @@protoc_insertion_point(field_mutable:DataTypes.Location.unit_mac_address)
  return unit_mac_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Location::release_unit_mac_address() {
  // @@protoc_insertion_point(field_release:DataTypes.Location.unit_mac_address)
  
  return unit_mac_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Location::set_allocated_unit_mac_address(::std::string* unit_mac_address) {
  if (unit_mac_address != NULL) {
    
  } else {
    
  }
  unit_mac_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), unit_mac_address);
  // @@protoc_insertion_point(field_set_allocated:DataTypes.Location.unit_mac_address)
}

// optional .DataTypes.AccessDevice access_device = 5;
bool Location::has_access_device() const {
  return !_is_default_instance_ && access_device_ != NULL;
}
void Location::clear_access_device() {
  if (GetArenaNoVirtual() == NULL && access_device_ != NULL) delete access_device_;
  access_device_ = NULL;
}
const ::DataTypes::AccessDevice& Location::access_device() const {
  // @@protoc_insertion_point(field_get:DataTypes.Location.access_device)
  return access_device_ != NULL ? *access_device_ : *default_instance_->access_device_;
}
::DataTypes::AccessDevice* Location::mutable_access_device() {
  
  if (access_device_ == NULL) {
    access_device_ = new ::DataTypes::AccessDevice;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.Location.access_device)
  return access_device_;
}
::DataTypes::AccessDevice* Location::release_access_device() {
  // @@protoc_insertion_point(field_release:DataTypes.Location.access_device)
  
  ::DataTypes::AccessDevice* temp = access_device_;
  access_device_ = NULL;
  return temp;
}
void Location::set_allocated_access_device(::DataTypes::AccessDevice* access_device) {
  delete access_device_;
  access_device_ = access_device;
  if (access_device) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.Location.access_device)
}

// optional .DataTypes.CaptureDevice capture_device = 6;
bool Location::has_capture_device() const {
  return !_is_default_instance_ && capture_device_ != NULL;
}
void Location::clear_capture_device() {
  if (GetArenaNoVirtual() == NULL && capture_device_ != NULL) delete capture_device_;
  capture_device_ = NULL;
}
const ::DataTypes::CaptureDevice& Location::capture_device() const {
  // @@protoc_insertion_point(field_get:DataTypes.Location.capture_device)
  return capture_device_ != NULL ? *capture_device_ : *default_instance_->capture_device_;
}
::DataTypes::CaptureDevice* Location::mutable_capture_device() {
  
  if (capture_device_ == NULL) {
    capture_device_ = new ::DataTypes::CaptureDevice;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.Location.capture_device)
  return capture_device_;
}
::DataTypes::CaptureDevice* Location::release_capture_device() {
  // @@protoc_insertion_point(field_release:DataTypes.Location.capture_device)
  
  ::DataTypes::CaptureDevice* temp = capture_device_;
  capture_device_ = NULL;
  return temp;
}
void Location::set_allocated_capture_device(::DataTypes::CaptureDevice* capture_device) {
  delete capture_device_;
  capture_device_ = capture_device;
  if (capture_device) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.Location.capture_device)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LocationUpdate::kInsertedFieldNumber;
const int LocationUpdate::kDeletedFieldNumber;
const int LocationUpdate::kUpdatedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LocationUpdate::LocationUpdate()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DataTypes.LocationUpdate)
}

void LocationUpdate::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  LocationUpdate_default_oneof_instance_->inserted_ = const_cast< ::DataTypes::Location*>(&::DataTypes::Location::default_instance());
  LocationUpdate_default_oneof_instance_->deleted_ = const_cast< ::DataTypes::Location*>(&::DataTypes::Location::default_instance());
  LocationUpdate_default_oneof_instance_->updated_ = const_cast< ::DataTypes::Location*>(&::DataTypes::Location::default_instance());
}

LocationUpdate::LocationUpdate(const LocationUpdate& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DataTypes.LocationUpdate)
}

void LocationUpdate::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  clear_has_update_type();
}

LocationUpdate::~LocationUpdate() {
  // @@protoc_insertion_point(destructor:DataTypes.LocationUpdate)
  SharedDtor();
}

void LocationUpdate::SharedDtor() {
  if (has_update_type()) {
    clear_update_type();
  }
  if (this != default_instance_) {
  }
}

void LocationUpdate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LocationUpdate::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LocationUpdate_descriptor_;
}

const LocationUpdate& LocationUpdate::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_datatypes_2flocation_2eproto();
  return *default_instance_;
}

LocationUpdate* LocationUpdate::default_instance_ = NULL;

LocationUpdate* LocationUpdate::New(::google::protobuf::Arena* arena) const {
  LocationUpdate* n = new LocationUpdate;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LocationUpdate::clear_update_type() {
// @@protoc_insertion_point(one_of_clear_start:DataTypes.LocationUpdate)
  switch(update_type_case()) {
    case kInserted: {
      delete update_type_.inserted_;
      break;
    }
    case kDeleted: {
      delete update_type_.deleted_;
      break;
    }
    case kUpdated: {
      delete update_type_.updated_;
      break;
    }
    case UPDATE_TYPE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = UPDATE_TYPE_NOT_SET;
}


void LocationUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:DataTypes.LocationUpdate)
  clear_update_type();
}

bool LocationUpdate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DataTypes.LocationUpdate)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .DataTypes.Location inserted = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_inserted()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_deleted;
        break;
      }

      // optional .DataTypes.Location deleted = 2;
      case 2: {
        if (tag == 18) {
         parse_deleted:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_deleted()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_updated;
        break;
      }

      // optional .DataTypes.Location updated = 3;
      case 3: {
        if (tag == 26) {
         parse_updated:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_updated()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DataTypes.LocationUpdate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DataTypes.LocationUpdate)
  return false;
#undef DO_
}

void LocationUpdate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DataTypes.LocationUpdate)
  // optional .DataTypes.Location inserted = 1;
  if (has_inserted()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *update_type_.inserted_, output);
  }

  // optional .DataTypes.Location deleted = 2;
  if (has_deleted()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *update_type_.deleted_, output);
  }

  // optional .DataTypes.Location updated = 3;
  if (has_updated()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *update_type_.updated_, output);
  }

  // @@protoc_insertion_point(serialize_end:DataTypes.LocationUpdate)
}

::google::protobuf::uint8* LocationUpdate::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataTypes.LocationUpdate)
  // optional .DataTypes.Location inserted = 1;
  if (has_inserted()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *update_type_.inserted_, target);
  }

  // optional .DataTypes.Location deleted = 2;
  if (has_deleted()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *update_type_.deleted_, target);
  }

  // optional .DataTypes.Location updated = 3;
  if (has_updated()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *update_type_.updated_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DataTypes.LocationUpdate)
  return target;
}

int LocationUpdate::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:DataTypes.LocationUpdate)
  int total_size = 0;

  switch (update_type_case()) {
    // optional .DataTypes.Location inserted = 1;
    case kInserted: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *update_type_.inserted_);
      break;
    }
    // optional .DataTypes.Location deleted = 2;
    case kDeleted: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *update_type_.deleted_);
      break;
    }
    // optional .DataTypes.Location updated = 3;
    case kUpdated: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *update_type_.updated_);
      break;
    }
    case UPDATE_TYPE_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LocationUpdate::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DataTypes.LocationUpdate)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const LocationUpdate* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LocationUpdate>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DataTypes.LocationUpdate)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DataTypes.LocationUpdate)
    MergeFrom(*source);
  }
}

void LocationUpdate::MergeFrom(const LocationUpdate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DataTypes.LocationUpdate)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  switch (from.update_type_case()) {
    case kInserted: {
      mutable_inserted()->::DataTypes::Location::MergeFrom(from.inserted());
      break;
    }
    case kDeleted: {
      mutable_deleted()->::DataTypes::Location::MergeFrom(from.deleted());
      break;
    }
    case kUpdated: {
      mutable_updated()->::DataTypes::Location::MergeFrom(from.updated());
      break;
    }
    case UPDATE_TYPE_NOT_SET: {
      break;
    }
  }
}

void LocationUpdate::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DataTypes.LocationUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LocationUpdate::CopyFrom(const LocationUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DataTypes.LocationUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocationUpdate::IsInitialized() const {

  return true;
}

void LocationUpdate::Swap(LocationUpdate* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LocationUpdate::InternalSwap(LocationUpdate* other) {
  std::swap(update_type_, other->update_type_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LocationUpdate::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LocationUpdate_descriptor_;
  metadata.reflection = LocationUpdate_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LocationUpdate

// optional .DataTypes.Location inserted = 1;
bool LocationUpdate::has_inserted() const {
  return update_type_case() == kInserted;
}
void LocationUpdate::set_has_inserted() {
  _oneof_case_[0] = kInserted;
}
void LocationUpdate::clear_inserted() {
  if (has_inserted()) {
    delete update_type_.inserted_;
    clear_has_update_type();
  }
}
 const ::DataTypes::Location& LocationUpdate::inserted() const {
  // @@protoc_insertion_point(field_get:DataTypes.LocationUpdate.inserted)
  return has_inserted()
      ? *update_type_.inserted_
      : ::DataTypes::Location::default_instance();
}
::DataTypes::Location* LocationUpdate::mutable_inserted() {
  if (!has_inserted()) {
    clear_update_type();
    set_has_inserted();
    update_type_.inserted_ = new ::DataTypes::Location;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.LocationUpdate.inserted)
  return update_type_.inserted_;
}
::DataTypes::Location* LocationUpdate::release_inserted() {
  // @@protoc_insertion_point(field_release:DataTypes.LocationUpdate.inserted)
  if (has_inserted()) {
    clear_has_update_type();
    ::DataTypes::Location* temp = update_type_.inserted_;
    update_type_.inserted_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LocationUpdate::set_allocated_inserted(::DataTypes::Location* inserted) {
  clear_update_type();
  if (inserted) {
    set_has_inserted();
    update_type_.inserted_ = inserted;
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.LocationUpdate.inserted)
}

// optional .DataTypes.Location deleted = 2;
bool LocationUpdate::has_deleted() const {
  return update_type_case() == kDeleted;
}
void LocationUpdate::set_has_deleted() {
  _oneof_case_[0] = kDeleted;
}
void LocationUpdate::clear_deleted() {
  if (has_deleted()) {
    delete update_type_.deleted_;
    clear_has_update_type();
  }
}
 const ::DataTypes::Location& LocationUpdate::deleted() const {
  // @@protoc_insertion_point(field_get:DataTypes.LocationUpdate.deleted)
  return has_deleted()
      ? *update_type_.deleted_
      : ::DataTypes::Location::default_instance();
}
::DataTypes::Location* LocationUpdate::mutable_deleted() {
  if (!has_deleted()) {
    clear_update_type();
    set_has_deleted();
    update_type_.deleted_ = new ::DataTypes::Location;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.LocationUpdate.deleted)
  return update_type_.deleted_;
}
::DataTypes::Location* LocationUpdate::release_deleted() {
  // @@protoc_insertion_point(field_release:DataTypes.LocationUpdate.deleted)
  if (has_deleted()) {
    clear_has_update_type();
    ::DataTypes::Location* temp = update_type_.deleted_;
    update_type_.deleted_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LocationUpdate::set_allocated_deleted(::DataTypes::Location* deleted) {
  clear_update_type();
  if (deleted) {
    set_has_deleted();
    update_type_.deleted_ = deleted;
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.LocationUpdate.deleted)
}

// optional .DataTypes.Location updated = 3;
bool LocationUpdate::has_updated() const {
  return update_type_case() == kUpdated;
}
void LocationUpdate::set_has_updated() {
  _oneof_case_[0] = kUpdated;
}
void LocationUpdate::clear_updated() {
  if (has_updated()) {
    delete update_type_.updated_;
    clear_has_update_type();
  }
}
 const ::DataTypes::Location& LocationUpdate::updated() const {
  // @@protoc_insertion_point(field_get:DataTypes.LocationUpdate.updated)
  return has_updated()
      ? *update_type_.updated_
      : ::DataTypes::Location::default_instance();
}
::DataTypes::Location* LocationUpdate::mutable_updated() {
  if (!has_updated()) {
    clear_update_type();
    set_has_updated();
    update_type_.updated_ = new ::DataTypes::Location;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.LocationUpdate.updated)
  return update_type_.updated_;
}
::DataTypes::Location* LocationUpdate::release_updated() {
  // @@protoc_insertion_point(field_release:DataTypes.LocationUpdate.updated)
  if (has_updated()) {
    clear_has_update_type();
    ::DataTypes::Location* temp = update_type_.updated_;
    update_type_.updated_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LocationUpdate::set_allocated_updated(::DataTypes::Location* updated) {
  clear_update_type();
  if (updated) {
    set_has_updated();
    update_type_.updated_ = updated;
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.LocationUpdate.updated)
}

bool LocationUpdate::has_update_type() const {
  return update_type_case() != UPDATE_TYPE_NOT_SET;
}
void LocationUpdate::clear_has_update_type() {
  _oneof_case_[0] = UPDATE_TYPE_NOT_SET;
}
LocationUpdate::UpdateTypeCase LocationUpdate::update_type_case() const {
  return LocationUpdate::UpdateTypeCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace DataTypes

// @@protoc_insertion_point(global_scope)
