// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes/visit_record.proto

#ifndef PROTOBUF_datatypes_2fvisit_5frecord_2eproto__INCLUDED
#define PROTOBUF_datatypes_2fvisit_5frecord_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "datatypes/card.pb.h"
#include "datatypes/key.pb.h"
#include "datatypes/datetime.pb.h"
#include "datatypes/biometrics.pb.h"
// @@protoc_insertion_point(includes)

namespace DataTypes {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_datatypes_2fvisit_5frecord_2eproto();
void protobuf_AssignDesc_datatypes_2fvisit_5frecord_2eproto();
void protobuf_ShutdownFile_datatypes_2fvisit_5frecord_2eproto();

class VisitRecord;
class VisitRecordUpdate;
class VisitRecordUpdates;

enum AccessState {
  NoneState = 0,
  Granted = 1,
  Denied = 2,
  AccessState_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  AccessState_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool AccessState_IsValid(int value);
const AccessState AccessState_MIN = NoneState;
const AccessState AccessState_MAX = Denied;
const int AccessState_ARRAYSIZE = AccessState_MAX + 1;

const ::google::protobuf::EnumDescriptor* AccessState_descriptor();
inline const ::std::string& AccessState_Name(AccessState value) {
  return ::google::protobuf::internal::NameOfEnum(
    AccessState_descriptor(), value);
}
inline bool AccessState_Parse(
    const ::std::string& name, AccessState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AccessState>(
    AccessState_descriptor(), name, value);
}
// ===================================================================

class VisitRecord : public ::google::protobuf::Message {
 public:
  VisitRecord();
  virtual ~VisitRecord();

  VisitRecord(const VisitRecord& from);

  inline VisitRecord& operator=(const VisitRecord& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VisitRecord& default_instance();

  void Swap(VisitRecord* other);

  // implements Message ----------------------------------------------

  inline VisitRecord* New() const { return New(NULL); }

  VisitRecord* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VisitRecord& from);
  void MergeFrom(const VisitRecord& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VisitRecord* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .DataTypes.Key id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::DataTypes::Key& id() const;
  ::DataTypes::Key* mutable_id();
  ::DataTypes::Key* release_id();
  void set_allocated_id(::DataTypes::Key* id);

  // optional .DataTypes.Key person_id = 2;
  bool has_person_id() const;
  void clear_person_id();
  static const int kPersonIdFieldNumber = 2;
  const ::DataTypes::Key& person_id() const;
  ::DataTypes::Key* mutable_person_id();
  ::DataTypes::Key* release_person_id();
  void set_allocated_person_id(::DataTypes::Key* person_id);

  // optional .DataTypes.Key location_id = 3;
  bool has_location_id() const;
  void clear_location_id();
  static const int kLocationIdFieldNumber = 3;
  const ::DataTypes::Key& location_id() const;
  ::DataTypes::Key* mutable_location_id();
  ::DataTypes::Key* release_location_id();
  void set_allocated_location_id(::DataTypes::Key* location_id);

  // optional .DataTypes.DateTime time = 4;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 4;
  const ::DataTypes::DateTime& time() const;
  ::DataTypes::DateTime* mutable_time();
  ::DataTypes::DateTime* release_time();
  void set_allocated_time(::DataTypes::DateTime* time);

  // optional .DataTypes.Card card = 5;
  bool has_card() const;
  void clear_card();
  static const int kCardFieldNumber = 5;
  const ::DataTypes::Card& card() const;
  ::DataTypes::Card* mutable_card();
  ::DataTypes::Card* release_card();
  void set_allocated_card(::DataTypes::Card* card);

  // optional .DataTypes.FaceCharacteristic face = 6;
  bool has_face() const;
  void clear_face();
  static const int kFaceFieldNumber = 6;
  const ::DataTypes::FaceCharacteristic& face() const;
  ::DataTypes::FaceCharacteristic* mutable_face();
  ::DataTypes::FaceCharacteristic* release_face();
  void set_allocated_face(::DataTypes::FaceCharacteristic* face);

  // optional .DataTypes.AccessState state = 7;
  void clear_state();
  static const int kStateFieldNumber = 7;
  ::DataTypes::AccessState state() const;
  void set_state(::DataTypes::AccessState value);

  // @@protoc_insertion_point(class_scope:DataTypes.VisitRecord)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::DataTypes::Key* id_;
  ::DataTypes::Key* person_id_;
  ::DataTypes::Key* location_id_;
  ::DataTypes::DateTime* time_;
  ::DataTypes::Card* card_;
  ::DataTypes::FaceCharacteristic* face_;
  int state_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_datatypes_2fvisit_5frecord_2eproto();
  friend void protobuf_AssignDesc_datatypes_2fvisit_5frecord_2eproto();
  friend void protobuf_ShutdownFile_datatypes_2fvisit_5frecord_2eproto();

  void InitAsDefaultInstance();
  static VisitRecord* default_instance_;
};
// -------------------------------------------------------------------

class VisitRecordUpdate : public ::google::protobuf::Message {
 public:
  VisitRecordUpdate();
  virtual ~VisitRecordUpdate();

  VisitRecordUpdate(const VisitRecordUpdate& from);

  inline VisitRecordUpdate& operator=(const VisitRecordUpdate& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VisitRecordUpdate& default_instance();

  enum RecordTypeCase {
    kInserted = 1,
    kDeleted = 2,
    kUpdated = 3,
    RECORD_TYPE_NOT_SET = 0,
  };

  void Swap(VisitRecordUpdate* other);

  // implements Message ----------------------------------------------

  inline VisitRecordUpdate* New() const { return New(NULL); }

  VisitRecordUpdate* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VisitRecordUpdate& from);
  void MergeFrom(const VisitRecordUpdate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VisitRecordUpdate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .DataTypes.VisitRecord inserted = 1;
  bool has_inserted() const;
  void clear_inserted();
  static const int kInsertedFieldNumber = 1;
  const ::DataTypes::VisitRecord& inserted() const;
  ::DataTypes::VisitRecord* mutable_inserted();
  ::DataTypes::VisitRecord* release_inserted();
  void set_allocated_inserted(::DataTypes::VisitRecord* inserted);

  // optional .DataTypes.VisitRecord deleted = 2;
  bool has_deleted() const;
  void clear_deleted();
  static const int kDeletedFieldNumber = 2;
  const ::DataTypes::VisitRecord& deleted() const;
  ::DataTypes::VisitRecord* mutable_deleted();
  ::DataTypes::VisitRecord* release_deleted();
  void set_allocated_deleted(::DataTypes::VisitRecord* deleted);

  // optional .DataTypes.VisitRecord updated = 3;
  bool has_updated() const;
  void clear_updated();
  static const int kUpdatedFieldNumber = 3;
  const ::DataTypes::VisitRecord& updated() const;
  ::DataTypes::VisitRecord* mutable_updated();
  ::DataTypes::VisitRecord* release_updated();
  void set_allocated_updated(::DataTypes::VisitRecord* updated);

  RecordTypeCase record_type_case() const;
  // @@protoc_insertion_point(class_scope:DataTypes.VisitRecordUpdate)
 private:
  inline void set_has_inserted();
  inline void set_has_deleted();
  inline void set_has_updated();

  inline bool has_record_type() const;
  void clear_record_type();
  inline void clear_has_record_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  union RecordTypeUnion {
    RecordTypeUnion() {}
    ::DataTypes::VisitRecord* inserted_;
    ::DataTypes::VisitRecord* deleted_;
    ::DataTypes::VisitRecord* updated_;
  } record_type_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_datatypes_2fvisit_5frecord_2eproto();
  friend void protobuf_AssignDesc_datatypes_2fvisit_5frecord_2eproto();
  friend void protobuf_ShutdownFile_datatypes_2fvisit_5frecord_2eproto();

  void InitAsDefaultInstance();
  static VisitRecordUpdate* default_instance_;
};
// -------------------------------------------------------------------

class VisitRecordUpdates : public ::google::protobuf::Message {
 public:
  VisitRecordUpdates();
  virtual ~VisitRecordUpdates();

  VisitRecordUpdates(const VisitRecordUpdates& from);

  inline VisitRecordUpdates& operator=(const VisitRecordUpdates& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VisitRecordUpdates& default_instance();

  void Swap(VisitRecordUpdates* other);

  // implements Message ----------------------------------------------

  inline VisitRecordUpdates* New() const { return New(NULL); }

  VisitRecordUpdates* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VisitRecordUpdates& from);
  void MergeFrom(const VisitRecordUpdates& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VisitRecordUpdates* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .DataTypes.VisitRecordUpdate items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::DataTypes::VisitRecordUpdate& items(int index) const;
  ::DataTypes::VisitRecordUpdate* mutable_items(int index);
  ::DataTypes::VisitRecordUpdate* add_items();
  ::google::protobuf::RepeatedPtrField< ::DataTypes::VisitRecordUpdate >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::DataTypes::VisitRecordUpdate >&
      items() const;

  // @@protoc_insertion_point(class_scope:DataTypes.VisitRecordUpdates)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::DataTypes::VisitRecordUpdate > items_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_datatypes_2fvisit_5frecord_2eproto();
  friend void protobuf_AssignDesc_datatypes_2fvisit_5frecord_2eproto();
  friend void protobuf_ShutdownFile_datatypes_2fvisit_5frecord_2eproto();

  void InitAsDefaultInstance();
  static VisitRecordUpdates* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// VisitRecord

// optional .DataTypes.Key id = 1;
inline bool VisitRecord::has_id() const {
  return !_is_default_instance_ && id_ != NULL;
}
inline void VisitRecord::clear_id() {
  if (GetArenaNoVirtual() == NULL && id_ != NULL) delete id_;
  id_ = NULL;
}
inline const ::DataTypes::Key& VisitRecord::id() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecord.id)
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
inline ::DataTypes::Key* VisitRecord::mutable_id() {
  
  if (id_ == NULL) {
    id_ = new ::DataTypes::Key;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecord.id)
  return id_;
}
inline ::DataTypes::Key* VisitRecord::release_id() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecord.id)
  
  ::DataTypes::Key* temp = id_;
  id_ = NULL;
  return temp;
}
inline void VisitRecord::set_allocated_id(::DataTypes::Key* id) {
  delete id_;
  id_ = id;
  if (id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecord.id)
}

// optional .DataTypes.Key person_id = 2;
inline bool VisitRecord::has_person_id() const {
  return !_is_default_instance_ && person_id_ != NULL;
}
inline void VisitRecord::clear_person_id() {
  if (GetArenaNoVirtual() == NULL && person_id_ != NULL) delete person_id_;
  person_id_ = NULL;
}
inline const ::DataTypes::Key& VisitRecord::person_id() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecord.person_id)
  return person_id_ != NULL ? *person_id_ : *default_instance_->person_id_;
}
inline ::DataTypes::Key* VisitRecord::mutable_person_id() {
  
  if (person_id_ == NULL) {
    person_id_ = new ::DataTypes::Key;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecord.person_id)
  return person_id_;
}
inline ::DataTypes::Key* VisitRecord::release_person_id() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecord.person_id)
  
  ::DataTypes::Key* temp = person_id_;
  person_id_ = NULL;
  return temp;
}
inline void VisitRecord::set_allocated_person_id(::DataTypes::Key* person_id) {
  delete person_id_;
  person_id_ = person_id;
  if (person_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecord.person_id)
}

// optional .DataTypes.Key location_id = 3;
inline bool VisitRecord::has_location_id() const {
  return !_is_default_instance_ && location_id_ != NULL;
}
inline void VisitRecord::clear_location_id() {
  if (GetArenaNoVirtual() == NULL && location_id_ != NULL) delete location_id_;
  location_id_ = NULL;
}
inline const ::DataTypes::Key& VisitRecord::location_id() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecord.location_id)
  return location_id_ != NULL ? *location_id_ : *default_instance_->location_id_;
}
inline ::DataTypes::Key* VisitRecord::mutable_location_id() {
  
  if (location_id_ == NULL) {
    location_id_ = new ::DataTypes::Key;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecord.location_id)
  return location_id_;
}
inline ::DataTypes::Key* VisitRecord::release_location_id() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecord.location_id)
  
  ::DataTypes::Key* temp = location_id_;
  location_id_ = NULL;
  return temp;
}
inline void VisitRecord::set_allocated_location_id(::DataTypes::Key* location_id) {
  delete location_id_;
  location_id_ = location_id;
  if (location_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecord.location_id)
}

// optional .DataTypes.DateTime time = 4;
inline bool VisitRecord::has_time() const {
  return !_is_default_instance_ && time_ != NULL;
}
inline void VisitRecord::clear_time() {
  if (GetArenaNoVirtual() == NULL && time_ != NULL) delete time_;
  time_ = NULL;
}
inline const ::DataTypes::DateTime& VisitRecord::time() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecord.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
inline ::DataTypes::DateTime* VisitRecord::mutable_time() {
  
  if (time_ == NULL) {
    time_ = new ::DataTypes::DateTime;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecord.time)
  return time_;
}
inline ::DataTypes::DateTime* VisitRecord::release_time() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecord.time)
  
  ::DataTypes::DateTime* temp = time_;
  time_ = NULL;
  return temp;
}
inline void VisitRecord::set_allocated_time(::DataTypes::DateTime* time) {
  delete time_;
  time_ = time;
  if (time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecord.time)
}

// optional .DataTypes.Card card = 5;
inline bool VisitRecord::has_card() const {
  return !_is_default_instance_ && card_ != NULL;
}
inline void VisitRecord::clear_card() {
  if (GetArenaNoVirtual() == NULL && card_ != NULL) delete card_;
  card_ = NULL;
}
inline const ::DataTypes::Card& VisitRecord::card() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecord.card)
  return card_ != NULL ? *card_ : *default_instance_->card_;
}
inline ::DataTypes::Card* VisitRecord::mutable_card() {
  
  if (card_ == NULL) {
    card_ = new ::DataTypes::Card;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecord.card)
  return card_;
}
inline ::DataTypes::Card* VisitRecord::release_card() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecord.card)
  
  ::DataTypes::Card* temp = card_;
  card_ = NULL;
  return temp;
}
inline void VisitRecord::set_allocated_card(::DataTypes::Card* card) {
  delete card_;
  card_ = card;
  if (card) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecord.card)
}

// optional .DataTypes.FaceCharacteristic face = 6;
inline bool VisitRecord::has_face() const {
  return !_is_default_instance_ && face_ != NULL;
}
inline void VisitRecord::clear_face() {
  if (GetArenaNoVirtual() == NULL && face_ != NULL) delete face_;
  face_ = NULL;
}
inline const ::DataTypes::FaceCharacteristic& VisitRecord::face() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecord.face)
  return face_ != NULL ? *face_ : *default_instance_->face_;
}
inline ::DataTypes::FaceCharacteristic* VisitRecord::mutable_face() {
  
  if (face_ == NULL) {
    face_ = new ::DataTypes::FaceCharacteristic;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecord.face)
  return face_;
}
inline ::DataTypes::FaceCharacteristic* VisitRecord::release_face() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecord.face)
  
  ::DataTypes::FaceCharacteristic* temp = face_;
  face_ = NULL;
  return temp;
}
inline void VisitRecord::set_allocated_face(::DataTypes::FaceCharacteristic* face) {
  delete face_;
  face_ = face;
  if (face) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecord.face)
}

// optional .DataTypes.AccessState state = 7;
inline void VisitRecord::clear_state() {
  state_ = 0;
}
inline ::DataTypes::AccessState VisitRecord::state() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecord.state)
  return static_cast< ::DataTypes::AccessState >(state_);
}
inline void VisitRecord::set_state(::DataTypes::AccessState value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:DataTypes.VisitRecord.state)
}

// -------------------------------------------------------------------

// VisitRecordUpdate

// optional .DataTypes.VisitRecord inserted = 1;
inline bool VisitRecordUpdate::has_inserted() const {
  return record_type_case() == kInserted;
}
inline void VisitRecordUpdate::set_has_inserted() {
  _oneof_case_[0] = kInserted;
}
inline void VisitRecordUpdate::clear_inserted() {
  if (has_inserted()) {
    delete record_type_.inserted_;
    clear_has_record_type();
  }
}
inline  const ::DataTypes::VisitRecord& VisitRecordUpdate::inserted() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecordUpdate.inserted)
  return has_inserted()
      ? *record_type_.inserted_
      : ::DataTypes::VisitRecord::default_instance();
}
inline ::DataTypes::VisitRecord* VisitRecordUpdate::mutable_inserted() {
  if (!has_inserted()) {
    clear_record_type();
    set_has_inserted();
    record_type_.inserted_ = new ::DataTypes::VisitRecord;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecordUpdate.inserted)
  return record_type_.inserted_;
}
inline ::DataTypes::VisitRecord* VisitRecordUpdate::release_inserted() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecordUpdate.inserted)
  if (has_inserted()) {
    clear_has_record_type();
    ::DataTypes::VisitRecord* temp = record_type_.inserted_;
    record_type_.inserted_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void VisitRecordUpdate::set_allocated_inserted(::DataTypes::VisitRecord* inserted) {
  clear_record_type();
  if (inserted) {
    set_has_inserted();
    record_type_.inserted_ = inserted;
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecordUpdate.inserted)
}

// optional .DataTypes.VisitRecord deleted = 2;
inline bool VisitRecordUpdate::has_deleted() const {
  return record_type_case() == kDeleted;
}
inline void VisitRecordUpdate::set_has_deleted() {
  _oneof_case_[0] = kDeleted;
}
inline void VisitRecordUpdate::clear_deleted() {
  if (has_deleted()) {
    delete record_type_.deleted_;
    clear_has_record_type();
  }
}
inline  const ::DataTypes::VisitRecord& VisitRecordUpdate::deleted() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecordUpdate.deleted)
  return has_deleted()
      ? *record_type_.deleted_
      : ::DataTypes::VisitRecord::default_instance();
}
inline ::DataTypes::VisitRecord* VisitRecordUpdate::mutable_deleted() {
  if (!has_deleted()) {
    clear_record_type();
    set_has_deleted();
    record_type_.deleted_ = new ::DataTypes::VisitRecord;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecordUpdate.deleted)
  return record_type_.deleted_;
}
inline ::DataTypes::VisitRecord* VisitRecordUpdate::release_deleted() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecordUpdate.deleted)
  if (has_deleted()) {
    clear_has_record_type();
    ::DataTypes::VisitRecord* temp = record_type_.deleted_;
    record_type_.deleted_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void VisitRecordUpdate::set_allocated_deleted(::DataTypes::VisitRecord* deleted) {
  clear_record_type();
  if (deleted) {
    set_has_deleted();
    record_type_.deleted_ = deleted;
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecordUpdate.deleted)
}

// optional .DataTypes.VisitRecord updated = 3;
inline bool VisitRecordUpdate::has_updated() const {
  return record_type_case() == kUpdated;
}
inline void VisitRecordUpdate::set_has_updated() {
  _oneof_case_[0] = kUpdated;
}
inline void VisitRecordUpdate::clear_updated() {
  if (has_updated()) {
    delete record_type_.updated_;
    clear_has_record_type();
  }
}
inline  const ::DataTypes::VisitRecord& VisitRecordUpdate::updated() const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecordUpdate.updated)
  return has_updated()
      ? *record_type_.updated_
      : ::DataTypes::VisitRecord::default_instance();
}
inline ::DataTypes::VisitRecord* VisitRecordUpdate::mutable_updated() {
  if (!has_updated()) {
    clear_record_type();
    set_has_updated();
    record_type_.updated_ = new ::DataTypes::VisitRecord;
  }
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecordUpdate.updated)
  return record_type_.updated_;
}
inline ::DataTypes::VisitRecord* VisitRecordUpdate::release_updated() {
  // @@protoc_insertion_point(field_release:DataTypes.VisitRecordUpdate.updated)
  if (has_updated()) {
    clear_has_record_type();
    ::DataTypes::VisitRecord* temp = record_type_.updated_;
    record_type_.updated_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void VisitRecordUpdate::set_allocated_updated(::DataTypes::VisitRecord* updated) {
  clear_record_type();
  if (updated) {
    set_has_updated();
    record_type_.updated_ = updated;
  }
  // @@protoc_insertion_point(field_set_allocated:DataTypes.VisitRecordUpdate.updated)
}

inline bool VisitRecordUpdate::has_record_type() const {
  return record_type_case() != RECORD_TYPE_NOT_SET;
}
inline void VisitRecordUpdate::clear_has_record_type() {
  _oneof_case_[0] = RECORD_TYPE_NOT_SET;
}
inline VisitRecordUpdate::RecordTypeCase VisitRecordUpdate::record_type_case() const {
  return VisitRecordUpdate::RecordTypeCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// VisitRecordUpdates

// repeated .DataTypes.VisitRecordUpdate items = 1;
inline int VisitRecordUpdates::items_size() const {
  return items_.size();
}
inline void VisitRecordUpdates::clear_items() {
  items_.Clear();
}
inline const ::DataTypes::VisitRecordUpdate& VisitRecordUpdates::items(int index) const {
  // @@protoc_insertion_point(field_get:DataTypes.VisitRecordUpdates.items)
  return items_.Get(index);
}
inline ::DataTypes::VisitRecordUpdate* VisitRecordUpdates::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:DataTypes.VisitRecordUpdates.items)
  return items_.Mutable(index);
}
inline ::DataTypes::VisitRecordUpdate* VisitRecordUpdates::add_items() {
  // @@protoc_insertion_point(field_add:DataTypes.VisitRecordUpdates.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::DataTypes::VisitRecordUpdate >*
VisitRecordUpdates::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:DataTypes.VisitRecordUpdates.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::DataTypes::VisitRecordUpdate >&
VisitRecordUpdates::items() const {
  // @@protoc_insertion_point(field_list:DataTypes.VisitRecordUpdates.items)
  return items_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace DataTypes

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::DataTypes::AccessState> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DataTypes::AccessState>() {
  return ::DataTypes::AccessState_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_datatypes_2fvisit_5frecord_2eproto__INCLUDED
